<?php
$url = array(
"https://i.imgur.com/bIE0qpK.mp4",
"https://i.imgur.com/XvoEKCS.mp4",
"https://i.imgur.com/tMC7HQA.mp4",
"https://i.imgur.com/Xl2HpDd.mp4",
"https://i.imgur.com/OkE1FxU.mp4",
"https://i.imgur.com/1f8WTQn.mp4",
"https://i.imgur.com/GnPnQcY.mp4",
"https://i.imgur.com/DU5bMuJ.mp4",
"https://i.imgur.com/pJqo5dF.mp4",
"https://i.imgur.com/aPXMwog.mp4",
"https://i.imgur.com/0GAe6L8.mp4",
"https://i.imgur.com/kTg6HQY.mp4",
"https://i.imgur.com/kTg6HQY.mp4",
"https://i.imgur.com/3o2OW8J.mp4",
"https://i.imgur.com/9fYTwZk.mp4",
"https://i.imgur.com/3DmIJ1A.mp4",
"https://i.imgur.com/MAB9Md5.mp4",
"https://i.imgur.com/hU0GIDa.mp4",
"https://i.imgur.com/K601tWe.mp4",
"https://i.imgur.com/gf4aF0j.mp4",
"https://i.imgur.com/iByriFm.mp4",
"https://i.imgur.com/x2j6CmF.mp4",
"https://i.imgur.com/ghV6WRE.mp4",
"https://i.imgur.com/RJ0MzxB.mp4",
"https://i.imgur.com/CxMmz0u.mp4",
"https://i.imgur.com/0KslBt5.mp4",
"https://i.imgur.com/IJ8Ot9f.mp4",
"https://i.imgur.com/LSGdq0W.mp4",
"https://i.imgur.com/hGO4pbh.mp4",
"https://i.imgur.com/734OzKB.mp4",
"https://i.imgur.com/sXs5tE8.mp4",
"https://i.imgur.com/E2PDV2d.mp4",
"https://i.imgur.com/rieXmsP.mp4",
"https://i.imgur.com/TMccUBw.mp4",
"https://i.imgur.com/H8BnrhM.mp4",
"https://i.imgur.com/hw8oIT9.mp4",
"https://i.imgur.com/VwWGkHW.mp4",
"https://i.imgur.com/zAMfGkL.mp4",
"https://i.imgur.com/WB5VBuE.mp4",
"https://i.imgur.com/dabhhyM.mp4",
"https://i.imgur.com/WrOYXkW.mp4",
"https://i.imgur.com/rocqHUy.mp4",
"https://i.imgur.com/yf6HWsN.mp4",
"https://i.imgur.com/mCcTeoc.mp4",
"https://i.imgur.com/2pj8qp8.mp4",
"https://i.imgur.com/zPSgFeH.mp4",
"https://i.imgur.com/ekV59Al.mp4",
"https://i.imgur.com/ME1eK2N.mp4",
"https://i.imgur.com/UTbOtK6.mp4",
"https://i.imgur.com/MjE3ozb.mp4",
"https://i.imgur.com/BMe0ojY.mp4",
"https://i.imgur.com/yjSg4A8.mp4",
"https://i.imgur.com/xkkGXzb.mp4",
"https://i.imgur.com/q0AKGid.mp4",
"https://i.imgur.com/JI4uo1X.mp4",
"https://i.imgur.com/YV9VsFe.mp4",
"https://i.imgur.com/7LiXLCm.mp4",
"https://i.imgur.com/K4yuKRV.mp4",
"https://i.imgur.com/8b0SNHO.mp4",
"https://i.imgur.com/0WpMjq3.mp4",
"https://i.imgur.com/w2SkLFO.mp4",
"https://i.imgur.com/zu6k4Gl.mp4",
"https://i.imgur.com/1cSjpwf.mp4",
"https://i.imgur.com/wJyMKlK.mp4",
"https://i.imgur.com/75RN3JJ.mp4",
"https://i.imgur.com/5f9cs31.mp4",
"https://i.imgur.com/w9fDXN8.mp4",
"https://i.imgur.com/ob5C4SA.mp4",
"https://i.imgur.com/EoqpjyI.mp4",
"https://i.imgur.com/oBeM5et.mp4",
);
$tuandz = array_rand($url);
$tuandeeptry = $url [$tuandz];
$gaixinhtik = array(
"data" => $tuandeeptry,
"author" => "TuanDeepTry",
"success" => "true",
);
$rdimg = json_encode($gaixinhtik , JSON_UNESCAPED_UNICODE);

$i = ['\/v\/','\/','TuanDeepTry'];
$t = ['/v/','/','TuanDeepTry'];
$j = str_replace($i, $t, $rdimg);
echo $j;
