<?php
$url = array(
"https://i.imgur.com/bIE0qpK.mp4",
"https://i.imgur.com/XvoEKCS.mp4",
"https://i.imgur.com/tMC7HQA.mp4",
"https://i.imgur.com/Xl2HpDd.mp4",
"https://i.imgur.com/OkE1FxU.mp4",
"https://i.imgur.com/1f8WTQn.mp4",
"https://i.imgur.com/GnPnQcY.mp4",
"https://i.imgur.com/DU5bMuJ.mp4",
"https://i.imgur.com/pJqo5dF.mp4",
"https://i.imgur.com/aPXMwog.mp4",
"https://i.imgur.com/0GAe6L8.mp4",
"https://i.imgur.com/kTg6HQY.mp4",
"https://i.imgur.com/kTg6HQY.mp4",
"https://i.imgur.com/3o2OW8J.mp4",
"https://i.imgur.com/9fYTwZk.mp4",
"https://i.imgur.com/3DmIJ1A.mp4",
"https://i.imgur.com/MAB9Md5.mp4",
"https://i.imgur.com/hU0GIDa.mp4",
"https://i.imgur.com/K601tWe.mp4",
"https://i.imgur.com/gf4aF0j.mp4",
"https://i.imgur.com/iByriFm.mp4",
"https://i.imgur.com/x2j6CmF.mp4",
"https://i.imgur.com/ghV6WRE.mp4",
"https://i.imgur.com/RJ0MzxB.mp4",
"https://i.imgur.com/CxMmz0u.mp4",
"https://i.imgur.com/0KslBt5.mp4",
"https://i.imgur.com/IJ8Ot9f.mp4",
"https://i.imgur.com/LSGdq0W.mp4",
"https://files.fm/down.php?i=9x2kzqfmx",
"https://files.fm/down.php?i=wpun3vhrr",
"https://files.fm/down.php?i=s35fsxhms",
"https://files.fm/down.php?i=bg7728nty",
"https://files.fm/down.php?i=2bzj5cgq4",
"https://files.fm/down.php?i=ysk5zqgvz",
"https://files.fm/down.php?i=wgkx4zatx",
"https://files.fm/down.php?i=jus6ynhqf",
"https://files.fm/down.php?i=we3kkncn4",
"https://files.fm/down.php?i=45pqvea2x",
"https://files.fm/down.php?i=x7pfgknva",
"https://files.fm/down.php?i=8h6wav7ef",
"https://files.fm/down.php?i=yqs8z3bn6",
"https://files.fm/down.php?i=e9eauerm8",
"https://files.fm/down.php?i=g3224mxm5",
"https://files.fm/down.php?i=xfanq6p3t",
"https://files.fm/down.php?i=4ea67v6zn",
"https://files.fm/down.php?i=rd4pjrh8v",
"https://files.fm/down.php?i=bbagp84wj",
"https://files.fm/down.php?i=3ktbbz4bt",
"https://files.fm/down.php?i=n7a57c9eu",
"https://files.fm/down.php?i=3asubuhat",
"https://files.fm/down.php?i=xngfqjt9r",
"https://files.fm/down.php?i=7bewpr6mr",
"https://files.fm/down.php?i=dj9gdhnnr",
"https://files.fm/down.php?i=xu2ejf63v",
"https://files.fm/down.php?i=43reserbe",
"https://files.fm/down.php?i=b3yjx4sk4",
"https://files.fm/down.php?i=f4zqnkszz",
"https://files.fm/down.php?i=y7naa5req",
"https://files.fm/down.php?i=6bkejqxt3",
"https://files.fm/down.php?i=yhpc8ta3s",
"https://files.fm/down.php?i=n736kj9j6",
"https://files.fm/down.php?i=f829nkgmq",
"https://files.fm/down.php?i=w4ghsyuk3",
"https://files.fm/down.php?i=fb3gk7rke",
"https://files.fm/down.php?i=wqyvxy57r",
"https://files.fm/down.php?i=4tquxp8xv",
"https://files.fm/down.php?i=v8x3fmjaa",
"https://files.fm/down.php?i=axjnzzn3j",
);
$tuandz = array_rand($url);
$tuandeeptry = $url [$tuandz];
$gaixinhtik = array(
"data" => $tuandeeptry,
"author" => "Tuấn DeepTry",
"success" => "true",
);
$rdimg = json_encode($gaixinhtik , JSON_UNESCAPED_UNICODE);

$i = ['\/v\/','\/','Tuấn DeepTry'];
$t = ['/v/','/','Tuấn DeepTry'];
$j = str_replace($i, $t, $rdimg);
echo $j;
